function rawValue(token) {
  return token.original?.$value ?? token.original?.value ?? token.$value ?? token.value;
}

function tokenType(token) {
  return token.original?.$type ?? token.original?.type ?? token.$type ?? token.type ?? "unknown";
}

function scopeFor(token) {
  return token.name.split("-")[0];
}

function cssVariableFor(token) {
  return token.original?.$extensions?.flow?.cssVariable ?? `--${token.name}`;
}

function contractValue(token, outputReferences) {
  const original = String(rawValue(token));
  const reference = original.match(/^\{([^}]+)\}$/)?.[1] ?? null;
  if (outputReferences && reference) return `var(--${reference})`;
  return original;
}

function flatContract(dictionary, outputReferences = true) {
  const tokens = {};
  for (const token of dictionary.allTokens) {
    const cssVariable = cssVariableFor(token);
    const value = contractValue(token, outputReferences);
    const reference = String(rawValue(token)).match(/^\{(.+)\}$/)?.[1] ?? null;
    tokens[token.name] = {
      value,
      type: tokenType(token),
      scope: scopeFor(token),
      cssVariable,
      ...(reference ? { reference } : {}),
      ...(value.match(/^var\((--[a-z0-9-]+)\)$/) ? { cssReference: value.slice(4, -1) } : {}),
    };
  }
  return tokens;
}

function sanitizeIdentifier(name) {
  return name
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/^([0-9])/, "_$1");
}

function camelIdentifier(name) {
  return sanitizeIdentifier(name)
    .toLowerCase()
    .replace(/_([a-z0-9])/g, (_, char) => char.toUpperCase());
}

function pascalIdentifier(name) {
  const camel = camelIdentifier(name);
  return camel ? camel[0].toUpperCase() + camel.slice(1) : "Token";
}

function xmlEscape(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export default {
  source: [process.env.FLOW_STYLE_DICTIONARY_SOURCE ?? "packages/tokens/source/**/*.tokens.json"],
  hooks: {
    formats: {
      "flow/css-variables": ({ dictionary, options }) => {
        const tokens = flatContract(dictionary, options.outputReferences !== false);
        return [
          ":root {",
          ...Object.entries(tokens).map(([name, token]) => `  --${name}: ${token.value};`),
          "}",
          "",
        ].join("\n");
      },
      "flow/token-contract": ({ dictionary, options }) => `${JSON.stringify({
        name: "Flow design tokens",
        version: "0.1.0",
        format: "flow-token-contract@2",
        source: "packages/tokens/source/**/*.tokens.json",
        generatedBy: "style-dictionary",
        compatibleWith: ["style-dictionary"],
        tokens: flatContract(dictionary, options.outputReferences !== false),
      }, null, 2)}\n`,
      "flow/typescript-flat": ({ dictionary, options }) => {
        const tokens = flatContract(dictionary, options.outputReferences !== false);
        const names = Object.keys(tokens).sort();
        return [
          "export type FlowTokenName =",
          ...names.map((name, index) => `  | ${JSON.stringify(name)}${index === names.length - 1 ? ";" : ""}`),
          "",
          "export type FlowToken = {",
          "  readonly value: string;",
          "  readonly type: string;",
          "  readonly scope: string;",
          "  readonly cssVariable: `--${string}`;",
          "  readonly reference?: string;",
          "  readonly cssReference?: `--${string}`;",
          "};",
          "",
          `export const flowTokens = ${JSON.stringify(tokens, null, 2)} as const satisfies Record<FlowTokenName, FlowToken>;`,
          "",
          `export const flowTokenNames = ${JSON.stringify(names, null, 2)} as const satisfies readonly FlowTokenName[];`,
          "",
        ].join("\n");
      },
      "flow/dart": ({ dictionary, options }) => {
        const tokens = flatContract(dictionary, options.outputReferences !== false);
        const entries = Object.entries(tokens).sort(([a], [b]) => a.localeCompare(b));
        return [
          "// Generated by Style Dictionary. Do not edit by hand.",
          "class FlowTokens {",
          "  const FlowTokens._();",
          ...entries.map(([name, token]) => `  static const String ${camelIdentifier(name)} = ${JSON.stringify(token.value)};`),
          "",
          "  static const Map<String, String> values = {",
          ...entries.map(([name, token]) => `    ${JSON.stringify(name)}: ${JSON.stringify(token.value)},`),
          "  };",
          "}",
          "",
        ].join("\n");
      },
      "flow/android-xml": ({ dictionary, options }) => {
        const tokens = flatContract(dictionary, options.outputReferences !== false);
        const entries = Object.entries(tokens).sort(([a], [b]) => a.localeCompare(b));
        return [
          "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
          "<!-- Generated by Style Dictionary. Do not edit by hand. -->",
          "<resources>",
          ...entries.map(([name, token]) => `  <string name="${sanitizeIdentifier(name).toLowerCase()}">${xmlEscape(token.value)}</string>`),
          "</resources>",
          "",
        ].join("\n");
      },
      "flow/swift": ({ dictionary, options }) => {
        const tokens = flatContract(dictionary, options.outputReferences !== false);
        const entries = Object.entries(tokens).sort(([a], [b]) => a.localeCompare(b));
        return [
          "// Generated by Style Dictionary. Do not edit by hand.",
          "public enum FlowTokens {",
          ...entries.map(([name, token]) => `  public static let ${camelIdentifier(name)} = ${JSON.stringify(token.value)}`),
          "",
          "  public static let values: [String: String] = [",
          ...entries.map(([name, token]) => `    ${JSON.stringify(name)}: ${JSON.stringify(token.value)},`),
          "  ]",
          "}",
          "",
        ].join("\n");
      },
    },
  },
  platforms: {
    css: {
      buildPath: "packages/tokens/styles/",
      files: [
        {
          destination: "tokens.css",
          format: "flow/css-variables",
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    contract: {
      buildPath: "packages/tokens/",
      files: [
        {
          destination: "tokens.json",
          format: "flow/token-contract",
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    typescript: {
      buildPath: "packages/tokens/src/generated/",
      files: [
        {
          destination: "tokens.ts",
          format: "flow/typescript-flat",
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    flutter: {
      buildPath: "packages/tokens/dist/flutter/",
      files: [
        {
          destination: "flow_tokens.dart",
          format: "flow/dart",
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    android: {
      buildPath: "packages/tokens/dist/android/",
      files: [
        {
          destination: "flow_tokens.xml",
          format: "flow/android-xml",
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    ios: {
      buildPath: "packages/tokens/dist/ios/",
      files: [
        {
          destination: "FlowTokens.swift",
          format: "flow/swift",
          options: {
            outputReferences: true,
          },
        },
      ],
    },
  },
};
