function rawValue(token) {
  return token.original?.$value ?? token.original?.value ?? token.$value ?? token.value;
}

function tokenType(token) {
  return token.original?.$type ?? token.original?.type ?? token.$type ?? token.type ?? "unknown";
}

function scopeFor(token) {
  return token.name.split("-")[0];
}

function cssVariableFor(token) {
  return token.original?.$extensions?.flow?.cssVariable ?? `--${token.name}`;
}

function contractValue(token, outputReferences) {
  const original = String(rawValue(token));
  const reference = original.match(/^\{([^}]+)\}$/)?.[1] ?? null;
  if (outputReferences && reference) return `var(--${reference})`;
  return original;
}

function flatContract(dictionary, outputReferences = true) {
  const tokens = {};
  for (const token of dictionary.allTokens) {
    const cssVariable = cssVariableFor(token);
    const value = contractValue(token, outputReferences);
    const reference = String(rawValue(token)).match(/^\{(.+)\}$/)?.[1] ?? null;
    tokens[token.name] = {
      value,
      type: tokenType(token),
      scope: scopeFor(token),
      cssVariable,
      ...(reference ? { reference } : {}),
      ...(value.match(/^var\((--[a-z0-9-]+)\)$/) ? { cssReference: value.slice(4, -1) } : {}),
    };
  }
  return tokens;
}

function sanitizeIdentifier(name) {
  return name
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/^([0-9])/, "_$1");
}

function camelIdentifier(name) {
  return sanitizeIdentifier(name)
    .toLowerCase()
    .replace(/_([a-z0-9])/g, (_, char) => char.toUpperCase());
}

function pascalIdentifier(name) {
  const camel = camelIdentifier(name);
  return camel ? camel[0].toUpperCase() + camel.slice(1) : "Token";
}

function xmlEscape(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export default {
  source: [process.env.FLOW_STYLE_DICTIONARY_SOURCE ?? "packages/tokens/source/**/*.tokens.json"],
  hooks: {
    formats: {
      "flow/css-variables": ({ dictionary, options }) => {
        const tokens = flatContract(dictionary, options.outputReferences !== false);
        return [
          ":root {",
          ...Object.entries(tokens).map(([name, token]) => `  --${name}: ${token.value};`),
          "}",
          "",
        ].join("\n");
      },
      "flow/css-contexts": () => [
        "/* Generated by Style Dictionary. Do not edit by hand. */",
        "",
        ":where([data-density=\"sm\"], [data-density-context=\"sm\"], .density-sm) {",
        "  --sys-density-control-height: var(--ref-frame-height-control-md-compact);",
        "  --sys-density-control-padding-x: var(--ref-frame-space-4);",
        "  --sys-density-control-padding-y: var(--ref-frame-space-2);",
        "  --sys-density-panel-padding: var(--ref-frame-space-5);",
        "  --sys-density-card-padding: var(--ref-frame-space-5);",
        "  --sys-density-surface-padding: var(--ref-frame-space-8);",
        "  --sys-density-component-gap: var(--ref-frame-space-3);",
        "  --sys-density-component-gap-lg: var(--ref-frame-space-5);",
        "  --sys-density-subsection-gap: var(--ref-frame-space-6);",
        "  --sys-density-section-gap: var(--ref-frame-space-12);",
        "  --sys-density-page-gap: var(--ref-frame-space-16);",
        "  --sys-density-row-height: var(--ref-frame-height-control-sm);",
        "  --sys-density-doc-heading-size: var(--ref-voice-size-9);",
        "  --sys-density-doc-heading-line-height: var(--ref-voice-line-height-tight);",
        "  --sys-density-doc-body-size: var(--ref-voice-size-5);",
        "  --sys-density-doc-body-line-height: var(--ref-voice-line-height-relaxed);",
        "  --sys-density-doc-label-size: var(--ref-voice-size-3);",
        "  --sys-density-doc-card-title-size: var(--ref-voice-size-5);",
        "  --sys-density-doc-card-body-size: var(--ref-voice-size-5);",
        "  --sys-density-doc-card-min-block: calc(var(--sys-density-row-height) * 2);",
        "  --sys-density-doc-example-min-block: calc(var(--sys-density-row-height) * 3);",
        "}",
        "",
        ":where([data-density=\"md\"], [data-density-context=\"md\"], .density-md) {",
        "  --sys-density-control-height: var(--ref-frame-height-control-md);",
        "  --sys-density-control-padding-x: var(--ref-frame-space-5);",
        "  --sys-density-control-padding-y: var(--ref-frame-space-3);",
        "  --sys-density-panel-padding: var(--ref-frame-space-6);",
        "  --sys-density-card-padding: var(--ref-frame-space-6);",
        "  --sys-density-surface-padding: var(--ref-frame-space-12);",
        "  --sys-density-component-gap: var(--ref-frame-space-5);",
        "  --sys-density-component-gap-lg: var(--ref-frame-space-7);",
        "  --sys-density-subsection-gap: var(--ref-frame-space-9);",
        "  --sys-density-section-gap: var(--ref-frame-space-16);",
        "  --sys-density-page-gap: var(--ref-frame-space-20);",
        "  --sys-density-row-height: var(--ref-frame-height-control-md);",
        "  --sys-density-doc-heading-size: var(--ref-voice-size-10);",
        "  --sys-density-doc-heading-line-height: var(--ref-voice-line-height-tight);",
        "  --sys-density-doc-body-size: var(--ref-voice-size-6);",
        "  --sys-density-doc-body-line-height: var(--ref-voice-line-height-relaxed);",
        "  --sys-density-doc-label-size: var(--ref-voice-size-3);",
        "  --sys-density-doc-card-title-size: var(--ref-voice-size-6);",
        "  --sys-density-doc-card-body-size: var(--ref-voice-size-6);",
        "  --sys-density-doc-card-min-block: calc(var(--sys-density-row-height) * 2);",
        "  --sys-density-doc-example-min-block: calc(var(--sys-density-row-height) * 3);",
        "}",
        "",
        ":where([data-density=\"lg\"], [data-density-context=\"lg\"], .density-lg),",
        ".density-responsive {",
        "  --sys-density-control-height: var(--ref-frame-height-control-lg-comfortable);",
        "  --sys-density-control-padding-x: var(--ref-frame-space-8);",
        "  --sys-density-control-padding-y: var(--ref-frame-space-5);",
        "  --sys-density-panel-padding: var(--ref-frame-space-10);",
        "  --sys-density-card-padding: var(--ref-frame-space-10);",
        "  --sys-density-surface-padding: var(--ref-frame-space-24);",
        "  --sys-density-component-gap: var(--ref-frame-space-8);",
        "  --sys-density-component-gap-lg: var(--ref-frame-space-10);",
        "  --sys-density-subsection-gap: var(--ref-frame-space-16);",
        "  --sys-density-section-gap: var(--ref-frame-space-24);",
        "  --sys-density-page-gap: var(--ref-frame-space-32);",
        "  --sys-density-row-height: var(--ref-frame-height-control-lg-comfortable);",
        "  --sys-density-doc-heading-size: var(--ref-voice-size-11);",
        "  --sys-density-doc-heading-line-height: var(--ref-voice-line-height-tight);",
        "  --sys-density-doc-body-size: var(--ref-voice-size-8);",
        "  --sys-density-doc-body-line-height: var(--ref-voice-line-height-relaxed);",
        "  --sys-density-doc-label-size: var(--ref-voice-size-4);",
        "  --sys-density-doc-card-title-size: var(--ref-voice-size-8);",
        "  --sys-density-doc-card-body-size: var(--ref-voice-size-7);",
        "  --sys-density-doc-card-min-block: calc(var(--sys-density-row-height) * 2);",
        "  --sys-density-doc-example-min-block: calc(var(--sys-density-row-height) * 3);",
        "}",
        "",
        ":root {",
        "  --frame-grid-columns: var(--sys-frame-grid-sm-columns);",
        "  --frame-grid-gutter: var(--sys-frame-grid-sm-gutter);",
        "  --frame-grid-margin: var(--sys-frame-grid-sm-margin);",
        "  --frame-page-x: var(--frame-grid-margin);",
        "  --frame-section-y: var(--density-section-gap);",
        "  --frame-page-shell: calc(var(--sys-frame-content-max) + (var(--frame-page-x) * 2));",
        "  --frame-card-min: 16rem;",
        "}",
        "",
        "@media (min-width: 576px) {",
        "  :root {",
        "    --frame-grid-columns: var(--sys-frame-grid-md-columns);",
        "    --frame-grid-gutter: var(--sys-frame-grid-md-gutter);",
        "    --frame-grid-margin: var(--sys-frame-grid-md-margin);",
        "  }",
        "",
        "  .density-responsive {",
        "    --sys-density-control-height: var(--ref-frame-height-control-md);",
        "    --sys-density-control-padding-x: var(--ref-frame-space-5);",
        "    --sys-density-control-padding-y: var(--ref-frame-space-3);",
        "    --sys-density-panel-padding: var(--ref-frame-space-6);",
        "    --sys-density-card-padding: var(--ref-frame-space-6);",
        "    --sys-density-surface-padding: var(--ref-frame-space-12);",
        "    --sys-density-component-gap: var(--ref-frame-space-5);",
        "    --sys-density-component-gap-lg: var(--ref-frame-space-7);",
        "    --sys-density-subsection-gap: var(--ref-frame-space-9);",
        "    --sys-density-section-gap: var(--ref-frame-space-16);",
        "    --sys-density-page-gap: var(--ref-frame-space-20);",
        "    --sys-density-row-height: var(--ref-frame-height-control-md);",
        "    --sys-density-doc-heading-size: var(--ref-voice-size-10);",
        "    --sys-density-doc-heading-line-height: var(--ref-voice-line-height-tight);",
        "    --sys-density-doc-body-size: var(--ref-voice-size-6);",
        "    --sys-density-doc-body-line-height: var(--ref-voice-line-height-relaxed);",
        "    --sys-density-doc-label-size: var(--ref-voice-size-3);",
        "    --sys-density-doc-card-title-size: var(--ref-voice-size-6);",
        "    --sys-density-doc-card-body-size: var(--ref-voice-size-6);",
        "    --sys-density-doc-card-min-block: calc(var(--sys-density-row-height) * 2);",
        "    --sys-density-doc-example-min-block: calc(var(--sys-density-row-height) * 3);",
        "  }",
        "}",
        "",
        "@media (min-width: 992px) {",
        "  :root {",
        "    --frame-grid-columns: var(--sys-frame-grid-lg-columns);",
        "    --frame-grid-gutter: var(--sys-frame-grid-lg-gutter);",
        "    --frame-grid-margin: var(--sys-frame-grid-lg-margin);",
        "  }",
        "",
        "  .density-responsive {",
        "    --sys-density-control-height: var(--ref-frame-height-control-md);",
        "    --sys-density-control-padding-x: var(--ref-frame-space-5);",
        "    --sys-density-control-padding-y: var(--ref-frame-space-3);",
        "    --sys-density-panel-padding: var(--ref-frame-space-5);",
        "    --sys-density-card-padding: var(--ref-frame-space-5);",
        "    --sys-density-surface-padding: var(--ref-frame-space-5);",
        "    --sys-density-component-gap: var(--ref-frame-space-4);",
        "    --sys-density-component-gap-lg: var(--ref-frame-space-5);",
        "    --sys-density-subsection-gap: var(--ref-frame-space-6);",
        "    --sys-density-section-gap: var(--ref-frame-space-10);",
        "    --sys-density-page-gap: var(--ref-frame-space-12);",
        "    --sys-density-row-height: var(--ref-frame-height-control-md);",
        "    --sys-density-doc-heading-size: var(--ref-voice-size-9);",
        "    --sys-density-doc-heading-line-height: var(--ref-voice-line-height-tight);",
        "    --sys-density-doc-body-size: var(--ref-voice-size-7);",
        "    --sys-density-doc-body-line-height: var(--ref-voice-line-height-relaxed);",
        "    --sys-density-doc-label-size: var(--ref-voice-size-3);",
        "    --sys-density-doc-card-title-size: var(--ref-voice-size-7);",
        "    --sys-density-doc-card-body-size: var(--ref-voice-size-6);",
        "    --sys-density-doc-card-min-block: calc(var(--sys-density-row-height) * 2);",
        "    --sys-density-doc-example-min-block: calc(var(--sys-density-row-height) * 3);",
        "  }",
        "}",
        "",
        ":root[data-contrast=\"quiet\"],",
        "body[data-contrast=\"quiet\"] {",
        "  color-scheme: dark;",
        "  --sys-energy-surface-primary: var(--sys-energy-text-primary);",
        "  --sys-energy-surface-secondary: var(--sys-energy-text-primary);",
        "  --sys-energy-surface-raised: var(--sys-energy-text-secondary);",
        "  --sys-energy-surface-sunken: var(--sys-energy-text-primary);",
        "  --sys-energy-text-primary: var(--sys-energy-text-on-action);",
        "  --sys-energy-text-secondary: var(--ref-energy-neutral-200);",
        "  --sys-energy-text-tertiary: var(--ref-energy-neutral-300);",
        "  --sys-energy-text-on-action: var(--sys-energy-text-on-action);",
        "  --sys-energy-border-default: color-mix(in srgb, var(--sys-energy-text-on-action) 16%, transparent);",
        "  --sys-energy-border-strong: color-mix(in srgb, var(--sys-energy-text-on-action) 32%, transparent);",
        "  --sys-color-surface: var(--sys-energy-surface-raised);",
        "  --sys-color-surface-raised: color-mix(in srgb, var(--sys-energy-surface-raised) 88%, var(--sys-energy-text-on-action) 12%);",
        "  --sys-color-surface-sunken: var(--sys-energy-surface-sunken);",
        "  --sys-color-text: var(--sys-energy-text-primary);",
        "  --sys-color-text-muted: var(--sys-energy-text-secondary);",
        "  --sys-color-border: color-mix(in srgb, var(--sys-energy-text-on-action) 52%, transparent);",
        "  --sys-color-action: var(--sys-energy-action-primary);",
        "  --sys-color-action-hover: var(--ref-energy-blue-400);",
        "  --sys-color-action-text: var(--sys-energy-text-on-action);",
        "  --sys-color-focus: var(--sys-energy-action-primary);",
        "  --sys-color-success: var(--sys-energy-status-success);",
        "  --sys-color-warning: var(--sys-energy-status-warning);",
        "  --sys-color-danger: var(--sys-energy-status-error);",
        "}",
        "",
      ].join("\n"),
      "flow/token-contract": ({ dictionary, options }) => `${JSON.stringify({
        name: "Flow design tokens",
        version: "0.1.0",
        format: "flow-token-contract@2",
        source: "packages/tokens/source/**/*.tokens.json",
        generatedBy: "style-dictionary",
        compatibleWith: ["style-dictionary"],
        tokens: flatContract(dictionary, options.outputReferences !== false),
      }, null, 2)}\n`,
      "flow/typescript-flat": ({ dictionary, options }) => {
        const tokens = flatContract(dictionary, options.outputReferences !== false);
        const names = Object.keys(tokens).sort();
        return [
          "export type FlowTokenName =",
          ...names.map((name, index) => `  | ${JSON.stringify(name)}${index === names.length - 1 ? ";" : ""}`),
          "",
          "export type FlowToken = {",
          "  readonly value: string;",
          "  readonly type: string;",
          "  readonly scope: string;",
          "  readonly cssVariable: `--${string}`;",
          "  readonly reference?: string;",
          "  readonly cssReference?: `--${string}`;",
          "};",
          "",
          `export const flowTokens = ${JSON.stringify(tokens, null, 2)} as const satisfies Record<FlowTokenName, FlowToken>;`,
          "",
          `export const flowTokenNames = ${JSON.stringify(names, null, 2)} as const satisfies readonly FlowTokenName[];`,
          "",
        ].join("\n");
      },
      "flow/dart": ({ dictionary, options }) => {
        const tokens = flatContract(dictionary, options.outputReferences !== false);
        const entries = Object.entries(tokens).sort(([a], [b]) => a.localeCompare(b));
        return [
          "// Generated by Style Dictionary. Do not edit by hand.",
          "class FlowTokens {",
          "  const FlowTokens._();",
          ...entries.map(([name, token]) => `  static const String ${camelIdentifier(name)} = ${JSON.stringify(token.value)};`),
          "",
          "  static const Map<String, String> values = {",
          ...entries.map(([name, token]) => `    ${JSON.stringify(name)}: ${JSON.stringify(token.value)},`),
          "  };",
          "}",
          "",
        ].join("\n");
      },
      "flow/android-xml": ({ dictionary, options }) => {
        const tokens = flatContract(dictionary, options.outputReferences !== false);
        const entries = Object.entries(tokens).sort(([a], [b]) => a.localeCompare(b));
        return [
          "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
          "<!-- Generated by Style Dictionary. Do not edit by hand. -->",
          "<resources>",
          ...entries.map(([name, token]) => `  <string name="${sanitizeIdentifier(name).toLowerCase()}">${xmlEscape(token.value)}</string>`),
          "</resources>",
          "",
        ].join("\n");
      },
      "flow/swift": ({ dictionary, options }) => {
        const tokens = flatContract(dictionary, options.outputReferences !== false);
        const entries = Object.entries(tokens).sort(([a], [b]) => a.localeCompare(b));
        return [
          "// Generated by Style Dictionary. Do not edit by hand.",
          "public enum FlowTokens {",
          ...entries.map(([name, token]) => `  public static let ${camelIdentifier(name)} = ${JSON.stringify(token.value)}`),
          "",
          "  public static let values: [String: String] = [",
          ...entries.map(([name, token]) => `    ${JSON.stringify(name)}: ${JSON.stringify(token.value)},`),
          "  ]",
          "}",
          "",
        ].join("\n");
      },
    },
  },
  platforms: {
    css: {
      buildPath: "packages/tokens/styles/",
      files: [
        {
          destination: "tokens.css",
          format: "flow/css-variables",
          options: {
            outputReferences: true,
          },
        },
        {
          destination: "token-contexts.css",
          format: "flow/css-contexts",
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    contract: {
      buildPath: "packages/tokens/",
      files: [
        {
          destination: "tokens.json",
          format: "flow/token-contract",
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    typescript: {
      buildPath: "packages/tokens/src/generated/",
      files: [
        {
          destination: "tokens.ts",
          format: "flow/typescript-flat",
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    flutter: {
      buildPath: "packages/tokens/dist/flutter/",
      files: [
        {
          destination: "flow_tokens.dart",
          format: "flow/dart",
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    android: {
      buildPath: "packages/tokens/dist/android/",
      files: [
        {
          destination: "flow_tokens.xml",
          format: "flow/android-xml",
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    ios: {
      buildPath: "packages/tokens/dist/ios/",
      files: [
        {
          destination: "FlowTokens.swift",
          format: "flow/swift",
          options: {
            outputReferences: true,
          },
        },
      ],
    },
  },
};
