export const systemTokens = {
  color: {
    surface: "#ffffff",
    surfaceRaised: "#f7f8fb",
    text: "#15171c",
    textMuted: "#5f6673",
    border: "#d9dee8",
    action: "#d9232e",
    actionHover: "#b91d27",
    actionText: "#ffffff",
    focus: "#2458d3",
    success: "#147a3f",
    warning: "#8a5a00",
    danger: "#b42318",
  },
  space: {
    xs: "4px",
    sm: "8px",
    md: "12px",
    lg: "16px",
    xl: "24px",
  },
  radius: {
    sm: "4px",
    md: "8px",
  },
  typography: {
    bodyFamily: "Ubuntu, system-ui, sans-serif",
    titleFamily: "Edenred, Ubuntu, system-ui, sans-serif",
  },
  energy: {
    action: {
      primary: "var(--sys-energy-action-primary)",
    },
    status: {
      success: "var(--sys-energy-status-success)",
      warning: "var(--sys-energy-status-warning)",
      warningForeground: "var(--sys-energy-status-warning-foreground)",
      error: "var(--sys-energy-status-error)",
    },
    surface: {
      primary: "var(--sys-energy-surface-primary)",
      secondary: "var(--sys-energy-surface-secondary)",
      tertiary: "var(--sys-energy-surface-tertiary)",
      sunken: "var(--sys-energy-surface-sunken)",
      accent: "var(--sys-energy-surface-accent)",
    },
    text: {
      primary: "var(--sys-energy-text-primary)",
      secondary: "var(--sys-energy-text-secondary)",
      tertiary: "var(--sys-energy-text-tertiary)",
      onAction: "var(--sys-energy-text-on-action)",
    },
    border: {
      default: "var(--sys-energy-border-default)",
      strong: "var(--sys-energy-border-strong)",
    },
    ref: {
      neutral: {
        50: "var(--ref-energy-neutral-50)",
        100: "var(--ref-energy-neutral-100)",
        200: "var(--ref-energy-neutral-200)",
        300: "var(--ref-energy-neutral-300)",
        400: "var(--ref-energy-neutral-400)",
        500: "var(--ref-energy-neutral-500)",
        600: "var(--ref-energy-neutral-600)",
        700: "var(--ref-energy-neutral-700)",
        800: "var(--ref-energy-neutral-800)",
        900: "var(--ref-energy-neutral-900)",
      },
      blue: {
        50: "var(--ref-energy-blue-50)",
        100: "var(--ref-energy-blue-100)",
        200: "var(--ref-energy-blue-200)",
        300: "var(--ref-energy-blue-300)",
        400: "var(--ref-energy-blue-400)",
        500: "var(--ref-energy-blue-500)",
        600: "var(--ref-energy-blue-600)",
        700: "var(--ref-energy-blue-700)",
        800: "var(--ref-energy-blue-800)",
        900: "var(--ref-energy-blue-900)",
      },
      red: {
        50: "var(--ref-energy-red-50)",
        100: "var(--ref-energy-red-100)",
        200: "var(--ref-energy-red-200)",
        300: "var(--ref-energy-red-300)",
        400: "var(--ref-energy-red-400)",
        500: "var(--ref-energy-red-500)",
        600: "var(--ref-energy-red-600)",
        700: "var(--ref-energy-red-700)",
        800: "var(--ref-energy-red-800)",
        900: "var(--ref-energy-red-900)",
      },
      green: {
        50: "var(--ref-energy-green-50)",
        100: "var(--ref-energy-green-100)",
        200: "var(--ref-energy-green-200)",
        300: "var(--ref-energy-green-300)",
        400: "var(--ref-energy-green-400)",
        500: "var(--ref-energy-green-500)",
        600: "var(--ref-energy-green-600)",
        700: "var(--ref-energy-green-700)",
        800: "var(--ref-energy-green-800)",
        900: "var(--ref-energy-green-900)",
      },
      yellow: {
        50: "var(--ref-energy-yellow-50)",
        100: "var(--ref-energy-yellow-100)",
        200: "var(--ref-energy-yellow-200)",
        300: "var(--ref-energy-yellow-300)",
        400: "var(--ref-energy-yellow-400)",
        500: "var(--ref-energy-yellow-500)",
        600: "var(--ref-energy-yellow-600)",
        700: "var(--ref-energy-yellow-700)",
        800: "var(--ref-energy-yellow-800)",
        900: "var(--ref-energy-yellow-900)",
      },
    },
  },
  voice: {
    family: {
      brand: "var(--ref-voice-family-brand)",
      sans: "var(--ref-voice-family-sans)",
      mono: "var(--ref-voice-family-mono)",
      control: "var(--sys-voice-family-control)",
    },
    transform: {
      none: "var(--sys-voice-transform-none)",
      uppercase: "var(--sys-voice-transform-uppercase)",
    },
    weight: {
      regular: "var(--ref-voice-weight-regular)",
      medium: "var(--ref-voice-weight-medium)",
      semibold: "var(--ref-voice-weight-semibold)",
      bold: "var(--ref-voice-weight-bold)",
      black: "var(--ref-voice-weight-black)",
      control: "var(--sys-voice-weight-control)",
    },
    role: {
      displayLg: {
        family: "var(--sys-voice-display-lg-family)",
        weight: "var(--sys-voice-display-lg-weight)",
        size: "var(--sys-voice-display-lg-size)",
        lineHeight: "var(--sys-voice-display-lg-line-height)",
        letterSpacing: "var(--sys-voice-display-lg-letter-spacing)",
      },
      displayMd: {
        family: "var(--sys-voice-display-md-family)",
        weight: "var(--sys-voice-display-md-weight)",
        size: "var(--sys-voice-display-md-size)",
        lineHeight: "var(--sys-voice-display-md-line-height)",
        letterSpacing: "var(--sys-voice-display-md-letter-spacing)",
      },
      displaySm: {
        family: "var(--sys-voice-display-sm-family)",
        weight: "var(--sys-voice-display-sm-weight)",
        size: "var(--sys-voice-display-sm-size)",
        lineHeight: "var(--sys-voice-display-sm-line-height)",
        letterSpacing: "var(--sys-voice-display-sm-letter-spacing)",
      },
      headingLg: {
        family: "var(--sys-voice-heading-lg-family)",
        weight: "var(--sys-voice-heading-lg-weight)",
        size: "var(--sys-voice-heading-lg-size)",
        lineHeight: "var(--sys-voice-heading-lg-line-height)",
        letterSpacing: "var(--sys-voice-heading-lg-letter-spacing)",
      },
      headingMd: {
        family: "var(--sys-voice-heading-md-family)",
        weight: "var(--sys-voice-heading-md-weight)",
        size: "var(--sys-voice-heading-md-size)",
        lineHeight: "var(--sys-voice-heading-md-line-height)",
        letterSpacing: "var(--sys-voice-heading-md-letter-spacing)",
      },
      headingSm: {
        family: "var(--sys-voice-heading-sm-family)",
        weight: "var(--sys-voice-heading-sm-weight)",
        size: "var(--sys-voice-heading-sm-size)",
        lineHeight: "var(--sys-voice-heading-sm-line-height)",
        letterSpacing: "var(--sys-voice-heading-sm-letter-spacing)",
      },
      labelLg: {
        family: "var(--sys-voice-family)",
        weight: "var(--sys-voice-weight-control)",
        size: "var(--sys-voice-label-lg-size)",
        lineHeight: "var(--sys-voice-label-lg-line-height)",
      },
      labelMd: {
        family: "var(--sys-voice-family)",
        weight: "var(--sys-voice-weight-control)",
        size: "var(--sys-voice-label-md-size)",
        lineHeight: "var(--sys-voice-label-md-line-height)",
      },
      labelSm: {
        family: "var(--sys-voice-family)",
        weight: "var(--sys-voice-weight-control)",
        size: "var(--sys-voice-label-sm-size)",
        lineHeight: "var(--sys-voice-label-sm-line-height)",
      },
      paragraphLg: {
        family: "var(--sys-voice-family)",
        weight: "var(--sys-voice-weight-regular)",
        size: "var(--sys-voice-paragraph-lg-size)",
        lineHeight: "var(--sys-voice-paragraph-lg-line-height)",
      },
      paragraphMd: {
        family: "var(--sys-voice-family)",
        weight: "var(--sys-voice-weight-regular)",
        size: "var(--sys-voice-paragraph-md-size)",
        lineHeight: "var(--sys-voice-paragraph-md-line-height)",
      },
      paragraphSm: {
        family: "var(--sys-voice-family)",
        weight: "var(--sys-voice-weight-regular)",
        size: "var(--sys-voice-paragraph-sm-size)",
        lineHeight: "var(--sys-voice-paragraph-sm-line-height)",
      },
      caption: {
        family: "var(--sys-voice-family)",
        weight: "var(--sys-voice-weight-medium)",
        size: "var(--sys-voice-caption-size)",
        lineHeight: "var(--sys-voice-caption-line-height)",
      },
      code: {
        family: "var(--sys-voice-family-mono)",
        weight: "var(--sys-voice-weight-semibold)",
        size: "var(--sys-voice-code-size)",
        lineHeight: "var(--sys-voice-code-line-height)",
      },
      numeral: {
        family: "var(--sys-voice-numeral-family)",
        weight: "var(--sys-voice-numeral-weight)",
        lineHeight: "var(--sys-voice-numeral-line-height)",
      },
    },
  },
  frame: {
    space: {
      0: "var(--ref-frame-space-0)",
      1: "var(--ref-frame-space-1)",
      2: "var(--ref-frame-space-2)",
      3: "var(--ref-frame-space-3)",
      4: "var(--ref-frame-space-4)",
      5: "var(--ref-frame-space-5)",
      6: "var(--ref-frame-space-6)",
      7: "var(--ref-frame-space-7)",
      8: "var(--ref-frame-space-8)",
      9: "var(--ref-frame-space-9)",
      10: "var(--ref-frame-space-10)",
      11: "var(--ref-frame-space-11)",
      12: "var(--ref-frame-space-12)",
      16: "var(--ref-frame-space-16)",
      20: "var(--ref-frame-space-20)",
      24: "var(--ref-frame-space-24)",
      32: "var(--ref-frame-space-32)",
      40: "var(--ref-frame-space-40)",
      micro: "var(--ref-frame-space-micro)",
    },
    radius: {
      0: "var(--ref-frame-radius-0)",
      1: "var(--ref-frame-radius-1)",
      2: "var(--ref-frame-radius-2)",
      3: "var(--ref-frame-radius-3)",
      4: "var(--ref-frame-radius-4)",
      5: "var(--ref-frame-radius-5)",
      6: "var(--ref-frame-radius-6)",
      7: "var(--ref-frame-radius-7)",
      8: "var(--ref-frame-radius-8)",
      9: "var(--ref-frame-radius-9)",
      10: "var(--ref-frame-radius-10)",
      11: "var(--ref-frame-radius-11)",
      12: "var(--ref-frame-radius-12)",
      control: "var(--sys-frame-radius-control)",
      container: "var(--sys-frame-radius-container)",
      surface: "var(--sys-frame-radius-surface)",
      full: "var(--sys-frame-radius-full)",
    },
    size: {
      controlSm: "var(--sys-frame-height-control-sm)",
      controlMd: "var(--sys-frame-height-control-md)",
      controlLg: "var(--sys-frame-height-control-lg)",
      row: "var(--sys-density-row-height)",
      sidebarExpanded: "var(--sys-frame-sidebar-expanded)",
      sidebarCollapsed: "var(--sys-frame-sidebar-collapsed)",
      contentMax: "var(--sys-frame-content-max)",
      contentDialog: "var(--sys-frame-content-dialog)",
      contentDrawerSm: "var(--sys-frame-content-drawer-sm)",
      contentDrawerMd: "var(--sys-frame-content-drawer-md)",
      contentDrawerLg: "var(--sys-frame-content-drawer-lg)",
      contentDatePanel: "var(--sys-frame-content-date-panel)",
      contentDateRangePanel: "var(--sys-frame-content-date-range-panel)",
      contentCountryListboxMaxInline: "var(--sys-frame-content-country-listbox-max-inline)",
      contentCountryListboxInline: "var(--sys-frame-content-country-listbox-inline)",
      contentPhoneInputFlexBasis: "var(--sys-frame-content-phone-input-flex-basis)",
      contentPhoneInputFlexBasisCompact: "var(--sys-frame-content-phone-input-flex-basis-compact)",
      contentPhoneInputMinInline: "var(--sys-frame-content-phone-input-min-inline)",
      contentPhoneInputMinInlineCompact: "var(--sys-frame-content-phone-input-min-inline-compact)",
      contentMetricMinXs: "var(--sys-frame-content-metric-min-xs)",
      contentMetricMinSm: "var(--sys-frame-content-metric-min-sm)",
      contentMetricMinMd: "var(--sys-frame-content-metric-min-md)",
      contentMetricMinLg: "var(--sys-frame-content-metric-min-lg)",
      contentActionLabelSm: "var(--sys-frame-content-action-label-sm)",
      contentActionLabelMd: "var(--sys-frame-content-action-label-md)",
      contentActionLabelLg: "var(--sys-frame-content-action-label-lg)",
      contentActionLabelXl: "var(--sys-frame-content-action-label-xl)",
      contentActionMinInlineSm: "var(--sys-frame-content-action-min-inline-sm)",
      contentActionMinInlineMd: "var(--sys-frame-content-action-min-inline-md)",
      contentActionMinInlineLg: "var(--sys-frame-content-action-min-inline-lg)",
      contentActionMinBlockMd: "var(--sys-frame-content-action-min-block-md)",
      contentActionMinBlockLg: "var(--sys-frame-content-action-min-block-lg)",
      contentDisclosureTriggerMinBlockSm: "var(--sys-frame-content-disclosure-trigger-min-block-sm)",
      contentDisclosureTriggerMinBlockMd: "var(--sys-frame-content-disclosure-trigger-min-block-md)",
      contentDisclosureTriggerMinBlockLg: "var(--sys-frame-content-disclosure-trigger-min-block-lg)",
      contentInlineTriggerMinBlockSm: "var(--sys-frame-content-inline-trigger-min-block-sm)",
      contentInlineTriggerMinBlockMd: "var(--sys-frame-content-inline-trigger-min-block-md)",
      contentInlineTriggerMinBlockLg: "var(--sys-frame-content-inline-trigger-min-block-lg)",
      contentNavigationTargetSm: "var(--sys-frame-content-navigation-target-sm)",
      contentNavigationTargetMd: "var(--sys-frame-content-navigation-target-md)",
      contentNavigationTargetLg: "var(--sys-frame-content-navigation-target-lg)",
      contentNavigationEllipsisInline: "var(--sys-frame-content-navigation-ellipsis-inline)",
      contentOptionMinBlock: "var(--sys-frame-content-option-min-block)",
      contentStepMarkerSm: "var(--sys-frame-content-step-marker-sm)",
      contentStepMarkerMd: "var(--sys-frame-content-step-marker-md)",
      contentStepMarkerLg: "var(--sys-frame-content-step-marker-lg)",
      contentStepTextMinInline: "var(--sys-frame-content-step-text-min-inline)",
      contentStepTextMaxInline: "var(--sys-frame-content-step-text-max-inline)",
      contentMenuMinSm: "var(--sys-frame-content-menu-min-sm)",
      contentMenuMinMd: "var(--sys-frame-content-menu-min-md)",
      contentMenuMinLg: "var(--sys-frame-content-menu-min-lg)",
    },
    ratio: {
      half: "var(--sys-frame-ratio-half)",
    },
    position: {
      center: "var(--sys-frame-position-center)",
    },
    density: {
      controlHeight: "var(--sys-density-control-height)",
      controlPaddingX: "var(--sys-density-control-padding-x)",
      controlPaddingY: "var(--sys-density-control-padding-y)",
      panelPadding: "var(--sys-density-panel-padding)",
      cardPadding: "var(--sys-density-card-padding)",
      surfacePadding: "var(--sys-density-surface-padding)",
      componentGap: "var(--sys-density-component-gap)",
      componentGapLg: "var(--sys-density-component-gap-lg)",
      subsectionGap: "var(--sys-density-subsection-gap)",
      sectionGap: "var(--sys-density-section-gap)",
      pageGap: "var(--sys-density-page-gap)",
      rowHeight: "var(--sys-density-row-height)",
    },
    grid: {
      sm: {
        columns: "var(--sys-frame-grid-sm-columns)",
        gutter: "var(--sys-frame-grid-sm-gutter)",
        margin: "var(--sys-frame-grid-sm-margin)",
      },
      md: {
        columns: "var(--sys-frame-grid-md-columns)",
        gutter: "var(--sys-frame-grid-md-gutter)",
        margin: "var(--sys-frame-grid-md-margin)",
      },
      lg: {
        columns: "var(--sys-frame-grid-lg-columns)",
        gutter: "var(--sys-frame-grid-lg-gutter)",
        margin: "var(--sys-frame-grid-lg-margin)",
        maxWidth: "var(--sys-frame-grid-lg-max-width)",
      },
    },
    breakpoint: {
      sm: "var(--sys-frame-breakpoint-sm)",
      shellSidebar: "var(--sys-frame-breakpoint-shell-sidebar)",
      md: "var(--sys-frame-breakpoint-md)",
      lg: "var(--sys-frame-breakpoint-lg)",
      xl: "var(--sys-frame-breakpoint-xl)",
    },
    border: {
      thin: "var(--sys-frame-border-thin)",
      control: "var(--sys-frame-border-control)",
      medium: "var(--sys-frame-border-medium)",
      indicator: "var(--sys-frame-border-indicator)",
    },
  },
  breakpoint: {
    mobile: "var(--sys-breakpoint-mobile)",
    tablet: "var(--sys-breakpoint-tablet)",
    shellSidebar: "var(--sys-frame-breakpoint-shell-sidebar)",
    laptop: "var(--sys-breakpoint-laptop)",
    desktop: "var(--sys-breakpoint-desktop)",
    wide: "var(--sys-breakpoint-wide)",
  },
  depth: {
    overlay: "var(--sys-depth-overlay)",
    backdropBlur: "var(--sys-depth-backdrop-blur)",
    blur: {
      sm: "var(--ref-depth-blur-sm)",
      md: "var(--ref-depth-blur-md)",
      lg: "var(--ref-depth-blur-lg)",
      topbar: "var(--sys-depth-blur-topbar)",
    },
    z: {
      dropdown: "var(--sys-depth-z-dropdown)",
      sticky: "var(--sys-depth-z-sticky)",
      overlay: "var(--sys-depth-z-overlay)",
      dialog: "var(--sys-depth-z-dialog)",
      toast: "var(--sys-depth-z-toast)",
    },
    lift: {
      subtle: "var(--sys-depth-lift-subtle)",
      rest: "var(--sys-depth-lift-rest)",
      raised: "var(--sys-depth-lift-raised)",
      overlay: "var(--sys-depth-lift-overlay)",
    },
    elevation: {
      0: "var(--sys-depth-elevation-0)",
      1: "var(--sys-depth-elevation-1)",
      2: "var(--sys-depth-elevation-2)",
      3: "var(--sys-depth-elevation-3)",
      4: "var(--sys-depth-elevation-4)",
    },
  },
  tone: {
    color: {
      neutral: "var(--sys-tone-neutral-color)",
      assistive: "var(--sys-tone-assistive-color)",
      urgent: "var(--sys-tone-urgent-color)",
      repair: "var(--sys-tone-repair-color)",
      confirm: "var(--sys-tone-confirm-color)",
    },
    weight: {
      neutral: "var(--sys-tone-neutral-weight)",
      assistive: "var(--sys-tone-assistive-weight)",
      urgent: "var(--sys-tone-urgent-weight)",
      repair: "var(--sys-tone-repair-weight)",
    },
  },
  accessibility: {
    focus: {
      ring: "var(--sys-a11y-focus-ring)",
      offset: "var(--sys-a11y-focus-offset)",
    },
    touch: {
      targetMin: "var(--sys-a11y-touch-target-min)",
    },
    contrast: {
      aa: "var(--sys-a11y-contrast-aa)",
      large: "var(--ref-a11y-contrast-large)",
    },
    motion: {
      reducedDuration: "var(--ref-a11y-motion-reduced-duration)",
      duration: "var(--sys-a11y-motion-duration)",
    },
  },
  message: {
    intent: {
      neutral: "var(--sys-message-intent-neutral-color)",
      assistive: "var(--sys-message-intent-assistive-color)",
      success: "var(--sys-message-intent-success-color)",
      warning: "var(--sys-message-intent-warning-color)",
      danger: "var(--sys-message-intent-danger-color)",
    },
    anatomy: {
      titleFont: "var(--sys-message-title-font)",
      titleWeight: "var(--sys-message-title-weight)",
      bodyFont: "var(--sys-message-body-font)",
      bodyWeight: "var(--sys-message-body-weight)",
      actionWeight: "var(--sys-message-action-weight)",
      recoveryWeight: "var(--sys-message-recovery-weight)",
    },
    accessibility: {
      liveRole: "var(--sys-message-live-role)",
      alertRole: "var(--sys-message-alert-role)",
      focusRing: "var(--sys-message-focus-ring)",
      readableLineHeight: "var(--sys-message-readable-line-height)",
    },
    localization: {
      maxInlineSize: "var(--sys-message-locale-max-inline-size)",
    },
  },
  symbol: {
    family: {
      material: "var(--ref-symbol-family-material)",
      default: "var(--sys-symbol-family)",
    },
    size: {
      xs: "var(--ref-symbol-size-xs)",
      sm: "var(--sys-symbol-size-sm)",
      md: "var(--sys-symbol-size-md)",
      lg: "var(--sys-symbol-size-lg)",
      xl: "var(--ref-symbol-size-xl)",
      gridBase: "var(--ref-symbol-grid-base)",
      liveArea: "var(--ref-symbol-live-area)",
    },
    stroke: "var(--ref-symbol-stroke)",
    color: {
      action: "var(--sys-symbol-color-action)",
      status: "var(--sys-symbol-color-status)",
      warning: "var(--sys-symbol-color-warning)",
      danger: "var(--sys-symbol-color-danger)",
      muted: "var(--sys-symbol-color-muted)",
    },
  },
  iconography: {
    family: "var(--sys-icon-family)",
    size: {
      sm: "var(--sys-icon-size-sm)",
      md: "var(--sys-icon-size-md)",
      lg: "var(--sys-icon-size-lg)",
    },
    color: {
      action: "var(--sys-icon-color-action)",
      navigation: "var(--sys-icon-color-navigation)",
      status: "var(--sys-icon-color-status)",
      warning: "var(--sys-icon-color-warning)",
      danger: "var(--sys-icon-color-danger)",
      muted: "var(--sys-icon-color-muted)",
      disabled: "var(--sys-icon-color-disabled)",
    },
    accessibility: {
      touchTargetMin: "var(--sys-icon-touch-target-min)",
      focusRing: "var(--sys-icon-focus-ring)",
      focusOffset: "var(--sys-icon-focus-offset)",
    },
  },
  growth: {
    stage: {
      seed: "var(--ref-growth-stage-seed)",
      stable: "var(--ref-growth-stage-stable)",
      measured: "var(--ref-growth-stage-measured)",
      deprecated: "var(--ref-growth-stage-deprecated)",
    },
    color: {
      seed: "var(--sys-growth-stage-seed-color)",
      stable: "var(--sys-growth-stage-stable-color)",
      measured: "var(--sys-growth-stage-measured-color)",
      deprecated: "var(--sys-growth-stage-deprecated-color)",
    },
    event: {
      font: "var(--sys-growth-event-font)",
    },
  },
  measurement: {
    event: {
      font: "var(--sys-measurement-event-font)",
      color: "var(--sys-measurement-event-color)",
    },
    metric: {
      font: "var(--sys-measurement-metric-font)",
      weight: "var(--sys-measurement-metric-weight)",
      color: "var(--sys-measurement-metric-color)",
    },
    analytics: {
      color: "var(--sys-measurement-analytics-color)",
    },
    hypothesis: {
      color: "var(--sys-measurement-hypothesis-color)",
    },
    guardrail: {
      color: "var(--sys-measurement-guardrail-color)",
      background: "var(--sys-measurement-guardrail-background)",
      privacyColor: "var(--sys-measurement-privacy-color)",
    },
  },
  chart: {
    series: {
      primary: "var(--sys-chart-series-primary)",
      secondary: "var(--sys-chart-series-secondary)",
      tertiary: "var(--sys-chart-series-tertiary)",
      quaternary: "var(--sys-chart-series-quaternary)",
    },
    threshold: {
      warning: "var(--sys-chart-threshold-warning)",
      danger: "var(--sys-chart-threshold-danger)",
    },
    axis: {
      color: "var(--sys-chart-axis-color)",
      grid: "var(--sys-chart-grid-color)",
    },
    legend: {
      textColor: "var(--sys-chart-legend-text-color)",
    },
    summary: {
      font: "var(--sys-chart-summary-font)",
      lineHeight: "var(--sys-chart-summary-line-height)",
    },
    empty: {
      color: "var(--sys-chart-empty-color)",
    },
    tooltip: {
      background: "var(--sys-chart-tooltip-background)",
      foreground: "var(--sys-chart-tooltip-foreground)",
    },
    accessibility: {
      focusRing: "var(--sys-chart-focus-ring)",
    },
    motion: {
      enterDuration: "var(--sys-chart-motion-duration-enter)",
      updateDuration: "var(--sys-chart-motion-duration-update)",
      enterEasing: "var(--sys-chart-motion-easing-enter)",
      updateEasing: "var(--sys-chart-motion-easing-update)",
    },
  },
  map: {
    permission: {
      granted: "var(--sys-map-permission-granted-color)",
      denied: "var(--sys-map-permission-denied-color)",
      prompt: "var(--sys-map-permission-prompt-color)",
    },
    pin: {
      background: "var(--sys-map-pin-background)",
      foreground: "var(--sys-map-pin-foreground)",
      border: "var(--sys-map-pin-border)",
      actionColor: "var(--sys-map-pin-action-color)",
      selectedBackground: "var(--sys-map-pin-selected-background)",
      selectedForeground: "var(--sys-map-pin-selected-foreground)",
      clusterBackground: "var(--sys-map-pin-cluster-background)",
      clusterForeground: "var(--sys-map-pin-cluster-foreground)",
    },
    route: {
      lineColor: "var(--sys-map-route-line-color)",
      mutedLineColor: "var(--sys-map-route-line-muted-color)",
    },
    fallback: {
      surface: "var(--sys-map-fallback-surface)",
      textColor: "var(--sys-map-fallback-text-color)",
    },
    depth: {
      pin: "var(--sys-map-depth-pin)",
      selected: "var(--sys-map-depth-selected)",
    },
    accessibility: {
      focusRing: "var(--sys-map-focus-ring)",
    },
  },
  research: {
    question: {
      font: "var(--sys-research-question-font)",
      weight: "var(--sys-research-question-weight)",
    },
    hypothesis: {
      color: "var(--sys-research-hypothesis-color)",
    },
    context: {
      color: "var(--sys-research-context-color)",
    },
    evidence: {
      color: "var(--sys-research-evidence-color)",
    },
    confidence: {
      low: "var(--sys-research-confidence-low-color)",
      medium: "var(--sys-research-confidence-medium-color)",
      high: "var(--sys-research-confidence-high-color)",
    },
    risk: {
      color: "var(--sys-research-risk-color)",
    },
    decisionLink: {
      color: "var(--sys-research-decision-link-color)",
    },
    accessibility: {
      readableLineHeight: "var(--sys-research-readable-line-height)",
    },
  },
  momentum: {
    duration: {
      instant: "var(--sys-duration-instant)",
      fast: "var(--sys-duration-fast)",
      default: "var(--sys-duration-base)",
      slow: "var(--sys-duration-slow)",
      critical: "var(--sys-duration-instant)",
      touch: "var(--sys-duration-touch)",
      cycle: "var(--sys-duration-cycle)",
    },
    easing: {
      touch: "var(--sys-motion-curve-touch)",
      standard: "var(--sys-motion-curve-standard)",
      enter: "var(--sys-motion-curve-enter)",
      move: "var(--sys-motion-curve-move)",
      exit: "var(--sys-motion-curve-exit)",
      linear: "var(--sys-motion-curve-linear)",
    },
    scale: {
      rest: "var(--sys-momentum-scale-rest)",
      none: "var(--sys-momentum-scale-none)",
      enter: "var(--sys-momentum-scale-enter)",
      quiet: "var(--sys-momentum-scale-quiet)",
      settle: "var(--sys-momentum-scale-settle)",
      raised: "var(--sys-momentum-scale-raised)",
      currentStart: "var(--sys-momentum-scale-current-start)",
      currentOvershoot: "var(--sys-momentum-scale-current-overshoot)",
      hover: "var(--sys-momentum-scale-hover)",
      press: "var(--sys-momentum-scale-press)",
    },
    progressTranslate: {
      start: "var(--sys-momentum-progress-translate-start)",
      mid: "var(--sys-momentum-progress-translate-mid)",
      end: "var(--sys-momentum-progress-translate-end)",
    },
    translate: {
      rest: "var(--sys-momentum-translate-rest)",
      inlineNudge: "var(--sys-momentum-translate-inline-nudge)",
    },
    cueTransform: {
      idle: "var(--sys-momentum-cue-transform-idle)",
      enter: "var(--sys-momentum-cue-transform-enter)",
      active: "var(--sys-momentum-cue-transform-active)",
      exit: "var(--sys-momentum-cue-transform-exit)",
    },
    rotate: {
      rest: "var(--sys-momentum-rotate-rest)",
      quarter: "var(--sys-momentum-rotate-quarter)",
      tilt: "var(--sys-momentum-rotate-tilt)",
      expanded: "var(--sys-momentum-rotate-expanded)",
      cycle: "var(--sys-momentum-rotate-cycle)",
    },
    lift: {
      hover: "var(--sys-momentum-lift-hover)",
    },
    stagger: {
      fast: "var(--ref-momentum-stagger-fast)",
      normal: "var(--ref-momentum-stagger-normal)",
      slow: "var(--ref-momentum-stagger-slow)",
    },
    transition: {
      touch: "var(--sys-momentum-transition-touch)",
      fast: "var(--sys-momentum-transition-fast)",
      default: "var(--sys-momentum-transition-default)",
      slow: "var(--sys-momentum-transition-slow)",
    },
  },
  state: {
    opacity: {
      hidden: "var(--sys-state-hidden-opacity)",
      disabled: "var(--sys-disabled-opacity)",
      muted: "var(--sys-state-muted-opacity)",
      faint: "var(--ref-state-opacity-faint)",
      subtle: "var(--ref-state-opacity-subtle)",
      low: "var(--ref-state-opacity-low)",
      soft: "var(--ref-state-opacity-soft)",
    },
    overlay: {
      hover: "var(--sys-state-hover-overlay)",
      pressed: "var(--sys-state-pressed-overlay)",
      selected: "var(--sys-state-selected-overlay)",
    },
    focus: {
      ring: "var(--sys-state-focus-ring)",
      offset: "var(--sys-state-focus-offset)",
      width: "var(--ref-state-focus-ring-width)",
    },
    loading: {
      spin: "var(--sys-loading-spin-duration)",
      cycle: "var(--sys-loading-cycle-duration)",
      progress: "var(--sys-loading-progress-duration)",
      pulse: "var(--sys-loading-pulse-duration)",
    },
    precedence: {
      disabled: "var(--ref-state-precedence-disabled)",
      loading: "var(--ref-state-precedence-loading)",
      error: "var(--ref-state-precedence-error)",
      focus: "var(--ref-state-precedence-focus)",
      hover: "var(--ref-state-precedence-hover)",
    },
  },
};

export function cssVar(name) {
  return `var(--sys-${name})`;
}
