import type { FlowTokenName } from "../generated/tokens";
import { createPrimitiveTokenResolver } from "./runtime";

export type TypographyPrimitiveTokenName = Extract<FlowTokenName, "sys-voice-caption-line-height" | "sys-voice-caption-size" | "sys-voice-code-line-height" | "sys-voice-code-size" | "sys-voice-code-sm-size" | "sys-voice-display-lg-family" | "sys-voice-display-lg-letter-spacing" | "sys-voice-display-lg-line-height" | "sys-voice-display-lg-size" | "sys-voice-display-lg-weight" | "sys-voice-display-md-family" | "sys-voice-display-md-letter-spacing" | "sys-voice-display-md-line-height" | "sys-voice-display-md-size" | "sys-voice-display-md-weight" | "sys-voice-display-sm-family" | "sys-voice-display-sm-letter-spacing" | "sys-voice-display-sm-line-height" | "sys-voice-display-sm-size" | "sys-voice-display-sm-weight" | "sys-voice-family" | "sys-voice-family-body" | "sys-voice-family-brand" | "sys-voice-family-control" | "sys-voice-family-mono" | "sys-voice-family-title" | "sys-voice-heading-lg-family" | "sys-voice-heading-lg-letter-spacing" | "sys-voice-heading-lg-line-height" | "sys-voice-heading-lg-size" | "sys-voice-heading-lg-weight" | "sys-voice-heading-md-family" | "sys-voice-heading-md-letter-spacing" | "sys-voice-heading-md-line-height" | "sys-voice-heading-md-size" | "sys-voice-heading-md-weight" | "sys-voice-heading-sm-family" | "sys-voice-heading-sm-letter-spacing" | "sys-voice-heading-sm-line-height" | "sys-voice-heading-sm-size" | "sys-voice-heading-sm-weight" | "sys-voice-label-lg-line-height" | "sys-voice-label-lg-size" | "sys-voice-label-md-line-height" | "sys-voice-label-md-size" | "sys-voice-label-sm-line-height" | "sys-voice-label-sm-size" | "sys-voice-letter-spacing-caps" | "sys-voice-letter-spacing-control" | "sys-voice-letter-spacing-expanded" | "sys-voice-letter-spacing-normal" | "sys-voice-letter-spacing-snug" | "sys-voice-letter-spacing-tight" | "sys-voice-letter-spacing-wide" | "sys-voice-letter-spacing-wider" | "sys-voice-letter-spacing-widest" | "sys-voice-line-height-balanced" | "sys-voice-line-height-body" | "sys-voice-line-height-body-sm" | "sys-voice-line-height-comfortable" | "sys-voice-line-height-compact" | "sys-voice-line-height-control" | "sys-voice-line-height-crisp" | "sys-voice-line-height-dense" | "sys-voice-line-height-display" | "sys-voice-line-height-loose" | "sys-voice-line-height-none" | "sys-voice-line-height-normal" | "sys-voice-line-height-reading" | "sys-voice-line-height-relaxed" | "sys-voice-line-height-snug" | "sys-voice-line-height-tight" | "sys-voice-line-height-tightest" | "sys-voice-numeral-family" | "sys-voice-numeral-lg-size" | "sys-voice-numeral-line-height" | "sys-voice-numeral-weight" | "sys-voice-overline-line-height" | "sys-voice-overline-size" | "sys-voice-paragraph-lg-line-height" | "sys-voice-paragraph-lg-size" | "sys-voice-paragraph-md-line-height" | "sys-voice-paragraph-md-size" | "sys-voice-paragraph-sm-line-height" | "sys-voice-paragraph-sm-size" | "sys-voice-size-1" | "sys-voice-size-10" | "sys-voice-size-11" | "sys-voice-size-12" | "sys-voice-size-13" | "sys-voice-size-14" | "sys-voice-size-2" | "sys-voice-size-3" | "sys-voice-size-4" | "sys-voice-size-5" | "sys-voice-size-6" | "sys-voice-size-7" | "sys-voice-size-8" | "sys-voice-size-9" | "sys-voice-size-body" | "sys-voice-size-body-sm" | "sys-voice-size-caption" | "sys-voice-size-label" | "sys-voice-size-overline" | "sys-voice-transform-none" | "sys-voice-transform-uppercase" | "sys-voice-weight-black" | "sys-voice-weight-bold" | "sys-voice-weight-control" | "sys-voice-weight-extrabold" | "sys-voice-weight-medium" | "sys-voice-weight-regular" | "sys-voice-weight-semibold">;

export const typographyPrimitive = {
  name: "Typography",
  slug: "typography",
  layer: "Primitive",
  runtimeKind: "runtime-contract",
  p0RuntimeRequired: true,
  policyPrimitive: false,
  purpose: "Turn Voice foundation roles into implementation-ready text primitives for display, headings, numerals, labels, body, captions, overline, and code.",
  governingFoundations: [
  "Voice",
  "Tone",
  "Frame",
  "Accessibility"
],
  coordinatesPrimitives: [
  "Density",
  "Spacing",
  "Breakpoints"
],
  tokenDependencies: [
  "ref.voice.*",
  "sys.voice.*",
  "sys.tone.*",
  "sys.frame.*",
  "sys.accessibility.*",
  "density.*",
  "spacing.*",
  "breakpoint.*",
  "typography.*",
  "comp.*.voice aliases"
],
  roles: [
  {
    "id": "display",
    "token": "typography.display.*",
    "use": "Template/page identity and major product moments with Edenred Black."
  },
  {
    "id": "heading",
    "token": "typography.heading.*",
    "use": "Section and panel hierarchy with Edenred Black."
  },
  {
    "id": "numeral",
    "token": "typography.numeral.*",
    "use": "KPIs, metrics, balances, counts, dashboard values, and prominent operational numbers with Edenred Black."
  },
  {
    "id": "label",
    "token": "typography.label.*",
    "use": "Controls, KPI labels, table headers, filters with Ubuntu."
  },
  {
    "id": "paragraph",
    "token": "typography.paragraph.*",
    "use": "Guidance, descriptions, empty/error copy with Ubuntu."
  },
  {
    "id": "caption",
    "token": "typography.caption",
    "use": "Metadata, helper text, timestamps, legal/support notes."
  },
  {
    "id": "code",
    "token": "typography.code.*",
    "use": "Token names, specs, API snippets, agent contracts."
  }
],
  states: [
  "default",
  "secondary",
  "disabled",
  "error",
  "warning",
  "success",
  "inverse",
  "truncated"
],
  rejectIf: [
  "Raw font-size, line-height, family, or weight appears in component CSS.",
  "Hero-scale text is used inside compact controls or dense panels.",
  "Error/repair copy lacks next action.",
  "Code/spec text is styled as body copy without distinction."
],
  tokenNames: [
  "sys-voice-caption-line-height",
  "sys-voice-caption-size",
  "sys-voice-code-line-height",
  "sys-voice-code-size",
  "sys-voice-code-sm-size",
  "sys-voice-display-lg-family",
  "sys-voice-display-lg-letter-spacing",
  "sys-voice-display-lg-line-height",
  "sys-voice-display-lg-size",
  "sys-voice-display-lg-weight",
  "sys-voice-display-md-family",
  "sys-voice-display-md-letter-spacing",
  "sys-voice-display-md-line-height",
  "sys-voice-display-md-size",
  "sys-voice-display-md-weight",
  "sys-voice-display-sm-family",
  "sys-voice-display-sm-letter-spacing",
  "sys-voice-display-sm-line-height",
  "sys-voice-display-sm-size",
  "sys-voice-display-sm-weight",
  "sys-voice-family",
  "sys-voice-family-body",
  "sys-voice-family-brand",
  "sys-voice-family-control",
  "sys-voice-family-mono",
  "sys-voice-family-title",
  "sys-voice-heading-lg-family",
  "sys-voice-heading-lg-letter-spacing",
  "sys-voice-heading-lg-line-height",
  "sys-voice-heading-lg-size",
  "sys-voice-heading-lg-weight",
  "sys-voice-heading-md-family",
  "sys-voice-heading-md-letter-spacing",
  "sys-voice-heading-md-line-height",
  "sys-voice-heading-md-size",
  "sys-voice-heading-md-weight",
  "sys-voice-heading-sm-family",
  "sys-voice-heading-sm-letter-spacing",
  "sys-voice-heading-sm-line-height",
  "sys-voice-heading-sm-size",
  "sys-voice-heading-sm-weight",
  "sys-voice-label-lg-line-height",
  "sys-voice-label-lg-size",
  "sys-voice-label-md-line-height",
  "sys-voice-label-md-size",
  "sys-voice-label-sm-line-height",
  "sys-voice-label-sm-size",
  "sys-voice-letter-spacing-caps",
  "sys-voice-letter-spacing-control",
  "sys-voice-letter-spacing-expanded",
  "sys-voice-letter-spacing-normal",
  "sys-voice-letter-spacing-snug",
  "sys-voice-letter-spacing-tight",
  "sys-voice-letter-spacing-wide",
  "sys-voice-letter-spacing-wider",
  "sys-voice-letter-spacing-widest",
  "sys-voice-line-height-balanced",
  "sys-voice-line-height-body",
  "sys-voice-line-height-body-sm",
  "sys-voice-line-height-comfortable",
  "sys-voice-line-height-compact",
  "sys-voice-line-height-control",
  "sys-voice-line-height-crisp",
  "sys-voice-line-height-dense",
  "sys-voice-line-height-display",
  "sys-voice-line-height-loose",
  "sys-voice-line-height-none",
  "sys-voice-line-height-normal",
  "sys-voice-line-height-reading",
  "sys-voice-line-height-relaxed",
  "sys-voice-line-height-snug",
  "sys-voice-line-height-tight",
  "sys-voice-line-height-tightest",
  "sys-voice-numeral-family",
  "sys-voice-numeral-lg-size",
  "sys-voice-numeral-line-height",
  "sys-voice-numeral-weight",
  "sys-voice-overline-line-height",
  "sys-voice-overline-size",
  "sys-voice-paragraph-lg-line-height",
  "sys-voice-paragraph-lg-size",
  "sys-voice-paragraph-md-line-height",
  "sys-voice-paragraph-md-size",
  "sys-voice-paragraph-sm-line-height",
  "sys-voice-paragraph-sm-size",
  "sys-voice-size-1",
  "sys-voice-size-10",
  "sys-voice-size-11",
  "sys-voice-size-12",
  "sys-voice-size-13",
  "sys-voice-size-14",
  "sys-voice-size-2",
  "sys-voice-size-3",
  "sys-voice-size-4",
  "sys-voice-size-5",
  "sys-voice-size-6",
  "sys-voice-size-7",
  "sys-voice-size-8",
  "sys-voice-size-9",
  "sys-voice-size-body",
  "sys-voice-size-body-sm",
  "sys-voice-size-caption",
  "sys-voice-size-label",
  "sys-voice-size-overline",
  "sys-voice-transform-none",
  "sys-voice-transform-uppercase",
  "sys-voice-weight-black",
  "sys-voice-weight-bold",
  "sys-voice-weight-control",
  "sys-voice-weight-extrabold",
  "sys-voice-weight-medium",
  "sys-voice-weight-regular",
  "sys-voice-weight-semibold"
] as const satisfies readonly TypographyPrimitiveTokenName[],
  token: createPrimitiveTokenResolver<TypographyPrimitiveTokenName>(["sys-voice-caption-line-height","sys-voice-caption-size","sys-voice-code-line-height","sys-voice-code-size","sys-voice-code-sm-size","sys-voice-display-lg-family","sys-voice-display-lg-letter-spacing","sys-voice-display-lg-line-height","sys-voice-display-lg-size","sys-voice-display-lg-weight","sys-voice-display-md-family","sys-voice-display-md-letter-spacing","sys-voice-display-md-line-height","sys-voice-display-md-size","sys-voice-display-md-weight","sys-voice-display-sm-family","sys-voice-display-sm-letter-spacing","sys-voice-display-sm-line-height","sys-voice-display-sm-size","sys-voice-display-sm-weight","sys-voice-family","sys-voice-family-body","sys-voice-family-brand","sys-voice-family-control","sys-voice-family-mono","sys-voice-family-title","sys-voice-heading-lg-family","sys-voice-heading-lg-letter-spacing","sys-voice-heading-lg-line-height","sys-voice-heading-lg-size","sys-voice-heading-lg-weight","sys-voice-heading-md-family","sys-voice-heading-md-letter-spacing","sys-voice-heading-md-line-height","sys-voice-heading-md-size","sys-voice-heading-md-weight","sys-voice-heading-sm-family","sys-voice-heading-sm-letter-spacing","sys-voice-heading-sm-line-height","sys-voice-heading-sm-size","sys-voice-heading-sm-weight","sys-voice-label-lg-line-height","sys-voice-label-lg-size","sys-voice-label-md-line-height","sys-voice-label-md-size","sys-voice-label-sm-line-height","sys-voice-label-sm-size","sys-voice-letter-spacing-caps","sys-voice-letter-spacing-control","sys-voice-letter-spacing-expanded","sys-voice-letter-spacing-normal","sys-voice-letter-spacing-snug","sys-voice-letter-spacing-tight","sys-voice-letter-spacing-wide","sys-voice-letter-spacing-wider","sys-voice-letter-spacing-widest","sys-voice-line-height-balanced","sys-voice-line-height-body","sys-voice-line-height-body-sm","sys-voice-line-height-comfortable","sys-voice-line-height-compact","sys-voice-line-height-control","sys-voice-line-height-crisp","sys-voice-line-height-dense","sys-voice-line-height-display","sys-voice-line-height-loose","sys-voice-line-height-none","sys-voice-line-height-normal","sys-voice-line-height-reading","sys-voice-line-height-relaxed","sys-voice-line-height-snug","sys-voice-line-height-tight","sys-voice-line-height-tightest","sys-voice-numeral-family","sys-voice-numeral-lg-size","sys-voice-numeral-line-height","sys-voice-numeral-weight","sys-voice-overline-line-height","sys-voice-overline-size","sys-voice-paragraph-lg-line-height","sys-voice-paragraph-lg-size","sys-voice-paragraph-md-line-height","sys-voice-paragraph-md-size","sys-voice-paragraph-sm-line-height","sys-voice-paragraph-sm-size","sys-voice-size-1","sys-voice-size-10","sys-voice-size-11","sys-voice-size-12","sys-voice-size-13","sys-voice-size-14","sys-voice-size-2","sys-voice-size-3","sys-voice-size-4","sys-voice-size-5","sys-voice-size-6","sys-voice-size-7","sys-voice-size-8","sys-voice-size-9","sys-voice-size-body","sys-voice-size-body-sm","sys-voice-size-caption","sys-voice-size-label","sys-voice-size-overline","sys-voice-transform-none","sys-voice-transform-uppercase","sys-voice-weight-black","sys-voice-weight-bold","sys-voice-weight-control","sys-voice-weight-extrabold","sys-voice-weight-medium","sys-voice-weight-regular","sys-voice-weight-semibold"]),
} as const;
